services:
  fastapi:
    container_name: fastapi
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - nginx
    env_file:
      - dev.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/fastapi.conf.template:/etc/nginx/nginx.conf.template
    ports:
      - "80:80"
    env_file:
      - dev.env
    command: ["sh", "-c", "envsubst < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf && nginx -g 'daemon off;'"]
