version: '3.8'

services:
 web:
    container_name: web
    build: .
    ports:
      - "8000:80"
    depends_on:
      - db
 db:
    container_name: db
    image: mongo
    ports:
      - "27017:27017"