services:
  fastapi:
    container_name: fastapi
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - nginx
    env_file:
      - dev.env
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/fastapi.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    env_file:
      - dev.env
