version: '3.8'

services:
  fastapi:
    container_name: fastapi
    build: .
    ports:
      - "8000:80"
    depends_on:
      - mongodb
      - milvus
    env_file:
      - dev.env
    networks:
      - fastapi-network